[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "2882"

[auth.google]
client_id = "610803646423-a0eedalk3fuedarpko3tvmhq045bhmdv.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url =  "https://accounts.google.com/.well-known/openid-configuration"


[mongo]
host = "localhost"
port = 8501
username = "parabaryan"
password = "v7tG302WB2BoHyL7"